/**
 * Printer catalog.
 *
 * Pure data. Nothing in the game reads a printer stat from anywhere else, and
 * the admin config layer can override or replace this list wholesale — the
 * game is not hard-coded around any particular brand or model list.
 */

import type { MaterialId, PrinterModelId } from '../types';

export interface PrinterModel {
  id: PrinterModelId;
  brand: string;
  name: string;
  family: string;
  /** Purchase price in Farm Coins. */
  price: number;
  /** Fraction of price recovered when sold at full health. */
  resaleFactor: number;
  /** Build volume in mm, for the spec sheet. */
  build: [number, number, number];
  /** Print-time multiplier. 1.0 is the baseline; lower is faster. */
  speed: number;
  /** 0..100. Raises delivered quality and lowers failure odds. */
  quality: number;
  /** Materials the machine can print. */
  materials: MaterialId[];
  multicolor: boolean;
  /** Watts drawn while printing. Used once the electricity system unlocks. */
  energy: number;
  /** 0..100. Higher reliability decays health more slowly. */
  reliability: number;
  /** Baseline failure probability per print, before health/material modifiers. */
  failureBase: number;
  /** Operating hours between recommended services. */
  maintenanceHours: number;
  upgradeSlots: number;
  queueCapacity: number;
  /** Grid footprint in cells. Industrial machines occupy more without breaking rows. */
  footprint: { w: number; h: number };
  /** Player level required before the shop lists it. */
  unlockLevel: number;
  /** Cost of a full repair when the machine has failed. */
  repairCost: number;
  /** Palette key used by the station sprite. */
  skin: 'cream' | 'charcoal' | 'orange' | 'red' | 'green' | 'steel';
}

export const PRINTER_CATALOG: PrinterModel[] = [
  {
    id: 'a1_mini',
    brand: 'Bambu Lab',
    name: 'A1 mini',
    family: 'A-series',
    price: 900,
    resaleFactor: 0.55,
    build: [180, 180, 180],
    speed: 1.0,
    quality: 62,
    materials: ['pla', 'petg', 'tpu'],
    multicolor: false,
    energy: 95,
    reliability: 62,
    failureBase: 0.06,
    maintenanceHours: 40,
    upgradeSlots: 2,
    queueCapacity: 3,
    footprint: { w: 1, h: 1 },
    unlockLevel: 1,
    repairCost: 160,
    skin: 'cream',
  },
  {
    id: 'a1_mini_combo',
    brand: 'Bambu Lab',
    name: 'A1 mini Combo',
    family: 'A-series',
    price: 1550,
    resaleFactor: 0.55,
    build: [180, 180, 180],
    speed: 0.98,
    quality: 66,
    materials: ['pla', 'petg', 'tpu'],
    multicolor: true,
    energy: 110,
    reliability: 64,
    failureBase: 0.06,
    maintenanceHours: 40,
    upgradeSlots: 3,
    queueCapacity: 4,
    footprint: { w: 1, h: 1 },
    unlockLevel: 3,
    repairCost: 220,
    skin: 'cream',
  },
  {
    id: 'a1',
    brand: 'Bambu Lab',
    name: 'A1',
    family: 'A-series',
    price: 2100,
    resaleFactor: 0.58,
    build: [256, 256, 256],
    speed: 0.86,
    quality: 71,
    materials: ['pla', 'petg', 'tpu'],
    multicolor: false,
    energy: 130,
    reliability: 70,
    failureBase: 0.05,
    maintenanceHours: 55,
    upgradeSlots: 3,
    queueCapacity: 4,
    footprint: { w: 1, h: 1 },
    unlockLevel: 5,
    repairCost: 300,
    skin: 'charcoal',
  },
  {
    id: 'a1_combo',
    brand: 'Bambu Lab',
    name: 'A1 Combo',
    family: 'A-series',
    price: 3200,
    resaleFactor: 0.58,
    build: [256, 256, 256],
    speed: 0.84,
    quality: 74,
    materials: ['pla', 'petg', 'tpu'],
    multicolor: true,
    energy: 150,
    reliability: 72,
    failureBase: 0.05,
    maintenanceHours: 55,
    upgradeSlots: 4,
    queueCapacity: 5,
    footprint: { w: 1, h: 1 },
    unlockLevel: 8,
    repairCost: 380,
    skin: 'charcoal',
  },
  {
    id: 'a2l',
    brand: 'Bambu Lab',
    name: 'A2L',
    family: 'A-series',
    price: 4400,
    resaleFactor: 0.6,
    build: [300, 300, 300],
    speed: 0.78,
    quality: 78,
    materials: ['pla', 'petg', 'tpu', 'abs'],
    multicolor: false,
    energy: 180,
    reliability: 76,
    failureBase: 0.045,
    maintenanceHours: 70,
    upgradeSlots: 4,
    queueCapacity: 5,
    footprint: { w: 1, h: 1 },
    unlockLevel: 12,
    repairCost: 520,
    skin: 'orange',
  },
  {
    id: 'a2l_combo',
    brand: 'Bambu Lab',
    name: 'A2L Combo',
    family: 'A-series',
    price: 6200,
    resaleFactor: 0.6,
    build: [300, 300, 300],
    speed: 0.76,
    quality: 81,
    materials: ['pla', 'petg', 'tpu', 'abs'],
    multicolor: true,
    energy: 205,
    reliability: 78,
    failureBase: 0.042,
    maintenanceHours: 70,
    upgradeSlots: 5,
    queueCapacity: 6,
    footprint: { w: 1, h: 1 },
    unlockLevel: 15,
    repairCost: 640,
    skin: 'orange',
  },
  {
    id: 'p1p',
    brand: 'Bambu Lab',
    name: 'P1P',
    family: 'P-series',
    price: 7600,
    resaleFactor: 0.6,
    build: [256, 256, 256],
    speed: 0.68,
    quality: 82,
    materials: ['pla', 'petg', 'tpu', 'abs', 'asa'],
    multicolor: false,
    energy: 230,
    reliability: 80,
    failureBase: 0.04,
    maintenanceHours: 85,
    upgradeSlots: 5,
    queueCapacity: 6,
    footprint: { w: 1, h: 1 },
    unlockLevel: 18,
    repairCost: 760,
    skin: 'charcoal',
  },
  {
    id: 'p2s',
    brand: 'Bambu Lab',
    name: 'P2S',
    family: 'P-series',
    price: 11000,
    resaleFactor: 0.62,
    build: [256, 256, 256],
    speed: 0.62,
    quality: 86,
    materials: ['pla', 'petg', 'tpu', 'abs', 'asa', 'pa'],
    multicolor: true,
    energy: 260,
    reliability: 84,
    failureBase: 0.035,
    maintenanceHours: 100,
    upgradeSlots: 6,
    queueCapacity: 7,
    footprint: { w: 1, h: 1 },
    unlockLevel: 22,
    repairCost: 1050,
    skin: 'green',
  },
  {
    id: 'x1c',
    brand: 'Bambu Lab',
    name: 'X1C',
    family: 'X-series',
    price: 16500,
    resaleFactor: 0.64,
    build: [256, 256, 256],
    speed: 0.55,
    quality: 91,
    materials: ['pla', 'petg', 'tpu', 'abs', 'asa', 'pa', 'pc', 'cf'],
    multicolor: true,
    energy: 300,
    reliability: 88,
    failureBase: 0.028,
    maintenanceHours: 120,
    upgradeSlots: 6,
    queueCapacity: 8,
    footprint: { w: 1, h: 1 },
    unlockLevel: 26,
    repairCost: 1550,
    skin: 'red',
  },
  {
    id: 'x2d',
    brand: 'Bambu Lab',
    name: 'X2D',
    family: 'X-series',
    price: 24000,
    resaleFactor: 0.65,
    build: [325, 325, 325],
    speed: 0.5,
    quality: 93,
    materials: ['pla', 'petg', 'tpu', 'abs', 'asa', 'pa', 'pc', 'cf'],
    multicolor: true,
    energy: 340,
    reliability: 90,
    failureBase: 0.025,
    maintenanceHours: 140,
    upgradeSlots: 7,
    queueCapacity: 8,
    footprint: { w: 1, h: 1 },
    unlockLevel: 30,
    repairCost: 2200,
    skin: 'red',
  },
  {
    id: 'h2s',
    brand: 'Bambu Lab',
    name: 'H2S',
    family: 'H-series',
    price: 34000,
    resaleFactor: 0.66,
    build: [350, 320, 325],
    speed: 0.46,
    quality: 94,
    materials: ['pla', 'petg', 'tpu', 'abs', 'asa', 'pa', 'pc', 'cf'],
    multicolor: true,
    energy: 400,
    reliability: 92,
    failureBase: 0.022,
    maintenanceHours: 160,
    upgradeSlots: 7,
    queueCapacity: 10,
    footprint: { w: 2, h: 1 },
    unlockLevel: 34,
    repairCost: 3100,
    skin: 'steel',
  },
  {
    id: 'h2d',
    brand: 'Bambu Lab',
    name: 'H2D',
    family: 'H-series',
    price: 46000,
    resaleFactor: 0.67,
    build: [350, 320, 325],
    speed: 0.42,
    quality: 96,
    materials: ['pla', 'petg', 'tpu', 'abs', 'asa', 'pa', 'pc', 'cf'],
    multicolor: true,
    energy: 460,
    reliability: 94,
    failureBase: 0.02,
    maintenanceHours: 180,
    upgradeSlots: 8,
    queueCapacity: 10,
    footprint: { w: 2, h: 1 },
    unlockLevel: 40,
    repairCost: 4200,
    skin: 'steel',
  },
  {
    id: 'h2c',
    brand: 'Bambu Lab',
    name: 'H2C',
    family: 'H-series',
    price: 68000,
    resaleFactor: 0.68,
    build: [400, 400, 400],
    speed: 0.38,
    quality: 98,
    materials: ['pla', 'petg', 'tpu', 'abs', 'asa', 'pa', 'pc', 'cf'],
    multicolor: true,
    energy: 560,
    reliability: 96,
    failureBase: 0.016,
    maintenanceHours: 220,
    upgradeSlots: 8,
    queueCapacity: 12,
    footprint: { w: 2, h: 2 },
    unlockLevel: 48,
    repairCost: 6400,
    skin: 'steel',
  },
];
